# Generated by Django 5.2 on 2025-04-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatbox_delete_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
